# Generated by Django 3.2.6 on 2021-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crud',
            options={'verbose_name': 'CRUD', 'verbose_name_plural': 'CRUD'},
        ),
        migrations.AddField(
            model_name='crud',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
